# These settings must match:
# - Port numbers specified in the ABB robot controller's system configurations for EGM communication.
egm:
  channel_1:
    port_number: 6512

# These settings must match:
# - Joint names extracted from the ABB robot controller.
#
# Please see http://wiki.ros.org/joint_limits_interface for more details about joint limits.
joint_limits:
  crb15000_joint_1:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 2.18166
    has_acceleration_limits: true
    max_acceleration: 50
  crb15000_joint_2:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 2.18166
    has_acceleration_limits: true
    max_acceleration: 50
  crb15000_joint_3:
    has_position_limits: true
    min_position: -3.92699
    max_position: 1.48353
    has_velocity_limits: true
    max_velocity: 2.44346
    has_acceleration_limits: true
    max_acceleration: 50
  crb15000_joint_4:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 3.49066
    has_acceleration_limits: true
    max_acceleration: 50
  crb15000_joint_5:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 3.49066
    has_acceleration_limits: true
    max_acceleration: 50
  crb15000_joint_6:
    has_position_limits: true
    min_position: -4.71239
    max_position: 4.71239
    has_velocity_limits: true
    max_velocity: 3.49066
    has_acceleration_limits: true
    max_acceleration: 50
